<?php

namespace UTravel\AdminBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends EntityRepository
{
    public function getMaxId()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('MAX(a.id)')->from('UTravelAdminBundle:Actualite', 'a');
        $result = $qb->getQuery()->getResult();
        return $result[0][1];
    }

    public function findActusFrom($max_id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
           ->from('UTravelAdminBundle:Actualite', 'a')
           ->where('a.id < :max_id')
           ->setParameter('max_id', $max_id)
           ->orderBy('a.dateCreation', 'DESC');
        return $qb->getQuery()->getResult();
    }
}