parameters:
#    u_travel_opinion.example.class: UTravel\OpinionBundle\Example

services:
#    u_travel_opinion.example:
#        class: %u_travel_opinion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    utravel.twig.opinion_extension:
        class: UTravel\OpinionBundle\Twig\TwigOpinionExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }
